# Generated by Django 4.0.6 on 2022-07-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='groupbalances',
            unique_together={('group', 'user_to_receive', 'user_to_pay')},
        ),
        migrations.AlterIndexTogether(
            name='groupbalances',
            index_together={('group', 'user_to_receive')},
        ),
    ]
